; Generated by evidc
target triple = "x86_64-pc-windows-msvc"

%evid.payload.Mode.Offline = type {}
%evid.payload.Mode.Online = type { i64 }
%evid.type.Mode = type { i32, [4 x i8], i64 }

define i64 @evid$render(%evid.type.Mode %arg0) {
entry:
  %slot0 = alloca %evid.type.Mode
  %slot1 = alloca i64
  %slot2 = alloca i64
  store %evid.type.Mode %arg0, ptr %slot0
  br label %bb0

bb0:
  %load0 = load %evid.type.Mode, ptr %slot0
  %ext1 = extractvalue %evid.type.Mode %load0, 0
  switch i32 %ext1, label %bb.trap.0 [
    i32 0, label %bb1
    i32 1, label %bb3
  ]

bb1:
  store i64 0, ptr %slot1
  br label %bb2

bb2:
  %load2 = load i64, ptr %slot1
  ret i64 %load2

bb3:
  %load3 = load %evid.type.Mode, ptr %slot0
  %ext4 = extractvalue %evid.type.Mode %load3, 2
  %unpack.slot5 = alloca i64
  store i64 %ext4, ptr %unpack.slot5
  %unpack6 = load %evid.payload.Mode.Online, ptr %unpack.slot5
  %ext7 = extractvalue %evid.payload.Mode.Online %unpack6, 0
  store i64 %ext7, ptr %slot2
  %load8 = load i64, ptr %slot2
  store i64 %load8, ptr %slot1
  br label %bb2

bb.trap.0:
  unreachable

}

