; Generated by evidc
target triple = "x86_64-pc-windows-msvc"

%evid.type.FileHandle = type { i64 }
%evid.payload.OpenFailure.FileNotFound = type { { ptr, i64 } }
%evid.type.OpenFailure = type { i32, [4 x i8], { i64, [8 x i8] } }

%evid.yield.boot = type { i8, [7 x i8], { i64, [16 x i8] } }

@evid.str.0 = private unnamed_addr constant [8 x i8] c"\6D\69\73\73\69\6E\67\00", align 1

define %evid.yield.boot @evid$boot() {
entry:
  %slot0 = alloca %evid.type.FileHandle
  %slot1 = alloca %evid.type.OpenFailure
  br label %bb0

bb0:
  %ins0 = insertvalue %evid.type.OpenFailure zeroinitializer, i32 0, 0
  %strptr1 = getelementptr inbounds [8 x i8], ptr @evid.str.0, i64 0, i64 0
  %ins2 = insertvalue { ptr, i64 } zeroinitializer, ptr %strptr1, 0
  %ins3 = insertvalue { ptr, i64 } %ins2, i64 7, 1
  %ins4 = insertvalue %evid.payload.OpenFailure.FileNotFound zeroinitializer, { ptr, i64 } %ins3, 0
  %pack.slot5 = alloca { i64, [8 x i8] }
  store { i64, [8 x i8] } zeroinitializer, ptr %pack.slot5
  store %evid.payload.OpenFailure.FileNotFound %ins4, ptr %pack.slot5
  %pack6 = load { i64, [8 x i8] }, ptr %pack.slot5
  %ins7 = insertvalue %evid.type.OpenFailure %ins0, { i64, [8 x i8] } %pack6, 2
  store %evid.type.OpenFailure %ins7, ptr %slot1
  %load8 = load %evid.type.OpenFailure, ptr %slot1
  %ins9 = insertvalue %evid.yield.boot zeroinitializer, i8 1, 0
  %pack.slot10 = alloca { i64, [16 x i8] }
  store { i64, [16 x i8] } zeroinitializer, ptr %pack.slot10
  store %evid.type.OpenFailure %load8, ptr %pack.slot10
  %pack11 = load { i64, [16 x i8] }, ptr %pack.slot10
  %ins12 = insertvalue %evid.yield.boot %ins9, { i64, [16 x i8] } %pack11, 2
  ret %evid.yield.boot %ins12

}

