; Generated by evidc
target triple = "x86_64-pc-windows-msvc"

%evid.type.RenderPassActive = type { i8 }
%evid.type.Mesh = type { i64 }
%evid.type.FrameReceipt = type { i64 }

define i8 @evid$start_pass() {
entry:
  %slot0 = alloca i8
  br label %bb0

bb0:
  store i8 0, ptr %slot0
  %load0 = load i8, ptr %slot0
  ret i8 %load0

}

define i64 @evid$submit(%evid.type.Mesh %arg0) {
entry:
  %slot1 = alloca %evid.type.Mesh
  %slot2 = alloca i64
  store %evid.type.Mesh %arg0, ptr %slot1
  br label %bb0

bb0:
  store i64 7, ptr %slot2
  %load0 = load i64, ptr %slot2
  ret i64 %load0

}

define %evid.type.FrameReceipt @evid$make_receipt(%evid.type.Mesh %arg0) {
entry:
  %slot0 = alloca %evid.type.Mesh
  %slot1 = alloca %evid.type.FrameReceipt
  store %evid.type.Mesh %arg0, ptr %slot0
  br label %bb0

bb0:
  %ins0 = insertvalue %evid.type.FrameReceipt zeroinitializer, i64 7, 0
  store %evid.type.FrameReceipt %ins0, ptr %slot1
  %load1 = load %evid.type.FrameReceipt, ptr %slot1
  ret %evid.type.FrameReceipt %load1

}

define %evid.type.FrameReceipt @evid$boot(%evid.type.Mesh %arg0) {
entry:
  %slot0 = alloca %evid.type.Mesh
  %slot1 = alloca %evid.type.FrameReceipt
  %slot2 = alloca i8
  %slot4 = alloca i64
  store %evid.type.Mesh %arg0, ptr %slot0
  br label %bb0

bb0:
  %call0 = call i8 @evid$start_pass()
  store i8 %call0, ptr %slot2
  %load1 = load %evid.type.Mesh, ptr %slot0
  %call2 = call i64 @evid$submit(%evid.type.Mesh %load1)
  store i64 %call2, ptr %slot4
  %load3 = load %evid.type.Mesh, ptr %slot0
  %call4 = call %evid.type.FrameReceipt @evid$make_receipt(%evid.type.Mesh %load3)
  store %evid.type.FrameReceipt %call4, ptr %slot1
  %load5 = load %evid.type.FrameReceipt, ptr %slot1
  ret %evid.type.FrameReceipt %load5

}

