; Generated by evidc
target triple = "x86_64-pc-windows-msvc"

%evid.type.FileHandle = type { i64 }
%evid.payload.OpenFailure.FileNotFound = type { { ptr, i64 } }
%evid.type.OpenFailure = type { i32, [4 x i8], { i64, [8 x i8] } }

%evid.yield.open = type { i8, [7 x i8], { i64, [16 x i8] } }
%evid.yield.boot = type { i8, [7 x i8], { i64, [16 x i8] } }

define %evid.yield.open @evid$open(i64 %arg0) {
entry:
  %slot0 = alloca i64
  %slot1 = alloca %evid.type.FileHandle
  store i64 %arg0, ptr %slot0
  br label %bb0

bb0:
  %load0 = load i64, ptr %slot0
  %ins1 = insertvalue %evid.type.FileHandle zeroinitializer, i64 %load0, 0
  store %evid.type.FileHandle %ins1, ptr %slot1
  %load2 = load %evid.type.FileHandle, ptr %slot1
  %ins3 = insertvalue %evid.yield.open zeroinitializer, i8 0, 0
  %pack.slot4 = alloca { i64, [16 x i8] }
  store { i64, [16 x i8] } zeroinitializer, ptr %pack.slot4
  store %evid.type.FileHandle %load2, ptr %pack.slot4
  %pack5 = load { i64, [16 x i8] }, ptr %pack.slot4
  %ins6 = insertvalue %evid.yield.open %ins3, { i64, [16 x i8] } %pack5, 2
  ret %evid.yield.open %ins6

}

define %evid.yield.boot @evid$boot(i64 %arg0) {
entry:
  %slot0 = alloca i64
  %slot1 = alloca %evid.type.FileHandle
  %slot2 = alloca %evid.type.OpenFailure
  store i64 %arg0, ptr %slot0
  br label %bb0

bb0:
  %load0 = load i64, ptr %slot0
  %invoke1 = call %evid.yield.open @evid$open(i64 %load0)
  %ext2 = extractvalue %evid.yield.open %invoke1, 0
  %ext3 = extractvalue %evid.yield.open %invoke1, 2
  %unpack.slot4 = alloca { i64, [16 x i8] }
  store { i64, [16 x i8] } %ext3, ptr %unpack.slot4
  %unpack5 = load %evid.type.FileHandle, ptr %unpack.slot4
  %unpack.slot6 = alloca { i64, [16 x i8] }
  store { i64, [16 x i8] } %ext3, ptr %unpack.slot6
  %unpack7 = load %evid.type.OpenFailure, ptr %unpack.slot6
  switch i8 %ext2, label %bb.trap.2 [
    i8 0, label %bb.invoke.ok.0
    i8 1, label %bb.invoke.fail.1
  ]

bb1:
  %load8 = load %evid.type.FileHandle, ptr %slot1
  %ins9 = insertvalue %evid.yield.boot zeroinitializer, i8 0, 0
  %pack.slot10 = alloca { i64, [16 x i8] }
  store { i64, [16 x i8] } zeroinitializer, ptr %pack.slot10
  store %evid.type.FileHandle %load8, ptr %pack.slot10
  %pack11 = load { i64, [16 x i8] }, ptr %pack.slot10
  %ins12 = insertvalue %evid.yield.boot %ins9, { i64, [16 x i8] } %pack11, 2
  ret %evid.yield.boot %ins12

bb2:
  %load13 = load %evid.type.OpenFailure, ptr %slot2
  %ins14 = insertvalue %evid.yield.boot zeroinitializer, i8 1, 0
  %pack.slot15 = alloca { i64, [16 x i8] }
  store { i64, [16 x i8] } zeroinitializer, ptr %pack.slot15
  store %evid.type.OpenFailure %load13, ptr %pack.slot15
  %pack16 = load { i64, [16 x i8] }, ptr %pack.slot15
  %ins17 = insertvalue %evid.yield.boot %ins14, { i64, [16 x i8] } %pack16, 2
  ret %evid.yield.boot %ins17

bb.invoke.ok.0:
  store %evid.type.FileHandle %unpack5, ptr %slot1
  br label %bb1

bb.invoke.fail.1:
  store %evid.type.OpenFailure %unpack7, ptr %slot2
  br label %bb2

bb.trap.2:
  unreachable

}

