if(NOT DEFINED SOURCE_DIR)
    message(FATAL_ERROR "SOURCE_DIR is required")
endif()

function(assert_doc_contains relative_path)
    set(doc_path "${SOURCE_DIR}/${relative_path}")
    if(NOT EXISTS "${doc_path}")
        message(FATAL_ERROR "expected release document does not exist: ${doc_path}")
    endif()

    file(READ "${doc_path}" doc_text)
    string(REPLACE "\r\n" "\n" doc_text "${doc_text}")
    string(REPLACE "\r" "\n" doc_text "${doc_text}")

    foreach(required_fragment IN LISTS ARGN)
        string(FIND "${doc_text}" "${required_fragment}" fragment_index)
        if(fragment_index EQUAL -1)
            message(FATAL_ERROR
                "release document ${relative_path} is missing expected text '${required_fragment}'")
        endif()
    endforeach()
endfunction()

function(assert_doc_does_not_contain relative_path forbidden_fragment)
    set(doc_path "${SOURCE_DIR}/${relative_path}")
    if(NOT EXISTS "${doc_path}")
        message(FATAL_ERROR "expected release document does not exist: ${doc_path}")
    endif()

    file(READ "${doc_path}" doc_text)
    string(REPLACE "\r\n" "\n" doc_text "${doc_text}")
    string(REPLACE "\r" "\n" doc_text "${doc_text}")

    string(FIND "${doc_text}" "${forbidden_fragment}" fragment_index)
    if(NOT fragment_index EQUAL -1)
        message(FATAL_ERROR
            "release document ${relative_path} still contains stale text '${forbidden_fragment}'")
    endif()
endfunction()

assert_doc_contains(README.md
    "## Supported validation matrix"
    "Windows x64"
    "MSVC x64 via CMake + Ninja"
    "x86_64-pc-windows-msvc"
    "LLVM `clang` with `lld-link`"
    "windows-2022"
    "manual `workflow_dispatch`"
    "public-repository push and manual `workflow_dispatch` builds"
    "windows-x64-ninja"
    "EVIDENT_CLANG=clang"
    "not yet a hermetic bit-for-bit reproducible build"
    "absolute resolved tool paths"
    "tool-version outputs that identify CMake, Ninja, clang, and LLD"
    "MSVC `cl` output identifying x64 target architecture"
    "compiler version output"
    "expected compiler toolchain fields"
    "selected driver that identifies clang"
    "checked-toolchain version probes identifying clang and LLD"
    "full source commit SHA"
    "validates that evidence file against the workflow `GITHUB_SHA` before upload"
    "current `403/403` CTest pass summary inside `[ctest output]`"
    "shared package checksum validator"
    "sidecar path, canonical text, filename, and ZIP bytes match"
    "revalidates the downloaded release evidence against the downloaded ZIP filename, byte size, SHA256, and workflow `GITHUB_SHA`"
    "a commit that does not match the expected source commit when one is supplied"
    "rejects missing runner image values, runner image OS output that does not identify Windows"
    "incomplete `[vswhere]` Visual Studio metadata"
    "MSVC compiler evidence that does not identify x64 target architecture"
    "mismatched top-level release scope fields"
    "duplicate singleton provenance fields"
    "duplicate evidence sections"
    "out-of-order evidence sections"
    "unexpected evidence sections"
    "empty tool-version or compiler toolchain output sections"
    "tool-version output that does not identify CMake, Ninja, clang, or LLD"
    "missing or mismatched compiler toolchain fields"
    "selected clang driver output that does not identify clang"
    "empty compiler toolchain version-probe lines"
    "checked-toolchain version output that does not identify clang or LLD"
    "compiler version output that does not match the release ZIP version"
    "extra validated commands"
    "misplaced CTest summaries"
    "package detail lines before `[release ZIP]`"
    "misplaced package details"
    "top provenance block records runner image OS identifying Windows and non-empty image version while matching the supported Windows x64 matrix"
    "selected Visual Studio path and version are recorded inside `[vswhere]`"
    "runs the read-only release source-tree audit before configure/build/test"
    "command list matches the supported release path exactly"
    "CTest pass summary is recorded inside `[ctest output]`"
    "package filename, size, and SHA256 are recorded inside `[release ZIP]`"
    "checksum writer rejects non-ZIP package paths"
    "output paths other than the package path plus `.sha256`"
    "package path to name a `.zip` archive"
    "sidecar path to be exactly the package path plus `.sha256`"
    "non-ZIP package paths"
    "misplaced checksum sidecar paths"
    "Every remote action reference used by that workflow is pinned to a full commit SHA"
    "rejects mutable official or third-party action tags"
    "The workflow keeps the build job `GITHUB_TOKEN` at `contents: read`"
    "unexpected `GITHUB_TOKEN` write permissions"
    "persist-credentials: false"
    "persisted checkout credentials"
    "unsafe or duplicate expected install allowlist paths"
    "validates the installed compiler as a PE executable"
    "unsafe expected install allowlist paths"
    "validates the packaged compiler as a PE executable"
    "checks packaged `--check-toolchain` output shape and verifies that the version probes identify clang and LLD"
    "sidecars missing the final newline"
    "sidecars with extra trailing blank lines"
    "unsafe, duplicate, or out-of-root expected package-entry allowlist paths"
    "bare package-root entries without a trailing slash"
    "empty path components"
    "tracked generated build, release, or local-only output before tagging"
    "release artifacts such as `evident-<version>-windows-x64.zip`, `<zip>.sha256`, `evident-release-evidence.txt`, and `release-artifact/`"
    "local-only artifacts such as `.vs/`, `.vscode/`, `.minimax/`, `.idea/`, `*.obj`, `.DS_Store`, and `repomix-output.txt`"
    "self-hosting or bootstrapping; the current compiler is still a C++23 seed compiler"
    "Bootstrap plan: `docs/BOOTSTRAP_PLAN.md`"
    "The first bootstrap-oriented Evident package outline lives under `bootstrap/compiler`."
    "package identity, a deterministic source-discovery plan, an original-file diagnostic anchor"
    "initial lexical token stream, parsed package syntax, and semantic symbol catalog models"
    "Its package identity now comes from the bootstrap environment surface"
    "host file, path, environment, and tool boundary models plus bootstrap stage-provenance and equivalence records"
    "`run_bootstrap_compiler_scaffold`"
)

assert_doc_contains(.gitignore
    "build/"
    "build-*/"
    "out/"
    "cmake-build-*/"
    "CMakeUserPresets.json"
    "CMakeCache.txt"
    "CMakeFiles/"
    "Testing/"
    "_CPack_Packages/"
    "evident-*-windows-x64.zip"
    "evident-*-windows-x64.zip.sha256"
    "evident-release-evidence.txt"
    "release-artifact/"
)

assert_doc_contains(CMakePresets.json
    "\"version\": 5"
    "\"major\": 3"
    "\"minor\": 24"
    "\"name\": \"windows-x64-ninja\""
    "\"generator\": \"Ninja\""
    "\"binaryDir\": \"\${sourceDir}/build/windows-x64-ninja\""
    "\"BUILD_TESTING\": \"ON\""
    "\"CMAKE_BUILD_TYPE\": \"Release\""
    "\"CMAKE_EXPORT_COMPILE_COMMANDS\": \"ON\""
    "\"EVIDENT_CLANG\": \"clang\""
    "\"type\": \"equals\""
    "\"lhs\": \"\${hostSystemName}\""
    "\"rhs\": \"Windows\""
    "\"name\": \"windows-x64-ninja-package\""
    "\"targets\""
    "\"package\""
    "\"name\": \"windows-x64-ninja-package-checksum\""
    "\"package_checksum\""
    "\"testPresets\""
    "\"outputOnFailure\": true"
)

assert_doc_contains(docs/RELEASE_CHECKLIST.md
    "## Supported Release Scope"
    "Anything outside this matrix is development work unless the supported validation matrix is updated first."
    "Host: Windows x64."
    "Build toolchain: CMake, Ninja, and MSVC x64 from an x64 Visual Studio developer shell."
    "Native target: `x86_64-pc-windows-msvc`."
    "Native emission toolchain: LLVM `clang` with `lld-link`, selected from `PATH` or through `EVIDENT_CLANG`."
    "the supported validation matrix in `README.md` still matches the commands above"
    "cmake -DSOURCE_DIR=. -P cmake/AssertReleaseSourceTree.cmake"
    "generated build, release, or local-only output paths"
    "root-level in-source CMake/Ninja/CTest/CPack artifacts such as `CMakeCache.txt`, `CMakeFiles/`, `build.ninja`, `Testing/`, or `_CPack_Packages/`"
    "release artifacts such as `evident-<version>-windows-x64.zip`, `<zip>.sha256`, `evident-release-evidence.txt`, or `release-artifact/`"
    "local-only artifacts such as `.vs/`, `.vscode/`, `.minimax/`, `.idea/`, `*.obj`, `.DS_Store`, or `repomix-output.txt` are tracked in source control"
    "the read-only release source-tree audit passes on the intended release branch"
    "manual `workflow_dispatch`"
    "public-repository push builds or manual `workflow_dispatch` release-validation runs"
    "full 40-character commit SHA"
    "matching `GITHUB_SHA` for CI builds"
    "source commit matching `GITHUB_SHA`"
    "runner image OS identifying Windows and non-empty image version"
    "source-tree audit status inside `[release source tree audit]`"
    "selected Visual Studio path and version inside `[vswhere]`"
    "MSVC `cl` output identifying x64 target architecture"
    "absolute resolved paths plus tool-version output identifying CMake, Ninja, clang, and LLD"
    "`evidc --version` output matching the version embedded in `evident-<version>-windows-x64.zip`"
    "`evidc --print-toolchain` output with expected native target, supported target, selected clang driver, override environment variable, and linker mode"
    "`evidc --check-toolchain` output with those expected fields plus version-probe lines identifying clang and LLD"
    "`evident-<version>-windows-x64.zip`"
    "normalizes CRLF/LF line endings"
    "one canonical line containing the ZIP SHA256 and ZIP filename followed by one final newline"
    "checksum writer rejects non-ZIP package paths"
    "checksum output paths other than the ZIP path plus `.sha256`"
    "package path to name a `.zip` archive"
    "requires the sidecar path to equal the ZIP path plus `.sha256`"
    "shared package checksum validator"
    "sidecar path, canonical text, filename, and ZIP bytes match"
    "unsafe or duplicate expected install allowlist paths"
    "validates the installed compiler as a PE executable"
    "unsafe expected install allowlist paths"
    "unsafe, duplicate, or out-of-root expected package-entry allowlist paths"
    "validates the packaged compiler as a PE executable"
    "checks packaged `--check-toolchain` output shape and verifies that the version probes identify clang and LLD"
    "misplaced checksum sidecar paths"
    "bare package-root entries without a trailing slash"
    "empty path components"
    "sidecars missing the final newline"
    "sidecars with extra trailing blank lines"
    "non-ZIP package paths"
    "current `403/403` CTest pass summary inside `[ctest output]`"
    "package filename, size, and SHA256 inside `[release ZIP]`"
    "MSVC `cl` output identifying x64 target architecture"
    "tool-version output identifying CMake, Ninja, clang, and LLD"
    "expected compiler toolchain fields including a selected driver that identifies clang"
    "checked-toolchain version probes identifying clang and LLD"
    "`evidc --version` output matching the version embedded in the release ZIP filename"
    "with no package detail lines before `[release ZIP]`"
    "top provenance block matching the supported Windows x64 matrix"
    "singleton fields and known sections present exactly once in the expected order"
    "no unexpected evidence sections"
    "validated command list matching the supported release path exactly"
    "including exact `<zip>.sha256` sidecar path and content binding"
    "matching `.sha256` file"
    "Every remote action reference on the release path is pinned to a full commit SHA"
    "rejects mutable official or third-party action tags"
    "every checkout step sets `persist-credentials: false`"
    "the build job keeps `GITHUB_TOKEN` at `contents: read`"
    "unexpected `GITHUB_TOKEN` write permissions"
    "persisted checkout credentials"
    "revalidates the downloaded release evidence file against the downloaded ZIP filename, byte size, SHA256, and `GITHUB_SHA` before provenance attestation generation and verification"
    "public GitHub Actions push or manual `workflow_dispatch` release-validation builds generate and verify artifact attestations"
    "This scope is still a seed-compiler release."
    "Do not describe a release as self-hosted or fully production-ready until the bootstrap evidence defined in `docs/BOOTSTRAP_PLAN.md` exists"
    "seed, stage-1, and stage-2 compiler provenance plus the stage-2 validation summary"
    "Do not describe a release as self-hosted or bootstrap-capable unless the additional gate in `docs/BOOTSTRAP_PLAN.md` passes"
)

assert_doc_contains(docs/TOOLCHAIN_REPRODUCIBILITY.md
    "## Supported Release Toolchain"
    "Hosted CI runner: GitHub Actions `windows-2022`."
    "CMake generator: Ninja through the `windows-x64-ninja` presets."
    "Native emission target: `x86_64-pc-windows-msvc`."
    "Native emission driver: LLVM `clang`, with `lld-link` available on `PATH`."
    "Current Evident release artifacts are **evidence-bound and locally rebuildable under the recorded environment**."
    "full 40-character source commit SHA"
    "matching `GITHUB_SHA` for CI builds"
    "runner label, runner image OS identifying Windows, and non-empty live image version"
    "Visual Studio installation path and version selected by `vswhere`"
    "release source-tree audit status inside `[release source tree audit]`"
    "absolute resolved paths for CMake, Ninja, `cl`, `clang`, and `lld-link`"
    "MSVC `cl` output identifying x64 target architecture"
    "tool-version output identifying CMake, Ninja, clang, and LLD"
    "`evidc --version` output matching the version embedded in the release ZIP filename"
    "`evidc --print-toolchain` output with expected native target, supported target, selected clang driver, override environment variable, and linker mode"
    "`evidc --check-toolchain` output with those expected fields plus version-probe lines identifying clang and LLD"
    "expected CTest `403/403` pass summary inside `[ctest output]`"
    "The read-only release source-tree audit passes on the intended release branch, including rejection of tracked generated build directories, `CMakeUserPresets.json`, root-level in-source CMake/Ninja/CTest/CPack artifacts, release ZIP/checksum/evidence artifacts, and ignored local-only artifacts."
    "install layout validation rejects unsafe or duplicate expected install allowlist paths"
    "validates the installed compiler as a PE executable"
    "`evident-<version>-windows-x64.zip`"
    "packaged compiler PE structure"
    "safe expected package-entry allowlist paths"
    "checksum-writer rejection of non-ZIP package paths"
    "misplaced checksum output paths"
    "canonical one-line `.sha256` sidecar validate"
    "exact `<zip>.sha256` sidecar path binding after CRLF/LF normalization"
    "exact `<zip>.sha256` sidecar path binding"
    "`evident-release-evidence.txt` passes `cmake/AssertReleaseEvidence.cmake`"
    "including tool-version output identifying CMake, Ninja, clang, and LLD"
    "expected compiler toolchain fields with a selected driver that identifies clang"
    "checked-toolchain version probes identifying clang and LLD"
    "the rule that package detail lines appear only inside `[release ZIP]`"
    "rejects missing runner image values, runner image OS output that does not identify Windows"
    "incomplete `[vswhere]` Visual Studio metadata"
    "MSVC compiler evidence that does not identify x64 target architecture"
    "missing `[release source tree audit]` status"
    "mismatched top-level release scope fields"
    "duplicate singleton provenance fields"
    "duplicate evidence sections"
    "unexpected evidence sections"
    "out-of-order evidence sections"
    "empty tool-version or compiler toolchain output sections"
    "tool-version output that does not identify CMake, Ninja, clang, or LLD"
    "missing or mismatched compiler toolchain fields"
    "selected clang driver output that does not identify clang"
    "empty compiler toolchain version-probe lines"
    "checked-toolchain version output that does not identify clang or LLD"
    "compiler version output that does not match the release ZIP version"
    "extra validated commands"
    "misplaced CTest summaries"
    "package detail lines before `[release ZIP]`"
    "misplaced package details"
    "top provenance block records runner image OS identifying Windows and non-empty image version while matching the supported Windows x64 matrix"
    "release source-tree audit pass line is recorded inside `[release source tree audit]`"
    "selected Visual Studio path and version are recorded inside `[vswhere]`"
    "command list matches the supported release path exactly"
    "CTest pass summary is recorded inside `[ctest output]`"
    "package filename, size, and SHA256 are recorded inside `[release ZIP]`"
    "GitHub artifact attestation status for public-repository push builds or manual `workflow_dispatch` release-validation runs"
    "The current release path is not self-hosting evidence."
    "stage-1 compiler built from the Evident compiler package"
    "stage-2 compiler rebuilt by stage 1 from the same package"
    "Any claim that a release is self-hosted or bootstrap-capable must include the seed, stage-1, and stage-2 evidence required by `docs/BOOTSTRAP_PLAN.md`."
    "validates the ZIP/checksum pair with `cmake/AssertPackageChecksum.cmake`"
    "checksum sidecar path to be the ZIP path plus `.sha256`"
    "same package checksum validator"
    "exactly one matching `<zip>.sha256` sidecar"
    "rechecks the downloaded ZIP and `.sha256` sidecar with the shared package checksum validator"
    "evidence commits that do not match the expected source commit when one is supplied"
    "revalidates the downloaded release evidence file against the downloaded ZIP filename, byte size, SHA256, and `GITHUB_SHA` before provenance attestation generation and verification"
    "The CI workflow runs the same release source-tree audit before configure/build/test."
    "requires every remote action reference to be pinned to a full commit SHA"
    "including any third-party action reference added later"
    "Checkout steps set `persist-credentials: false`"
    "Every remote action reference used by the release workflow is pinned to a full commit SHA"
    "Every checkout step used by the release workflow sets `persist-credentials: false`."
    "The build job keeps `GITHUB_TOKEN` at `contents: read`, and the attestation job grants only `actions: read`, `attestations: write`, `contents: read`, and `id-token: write`."
    "Do not claim a release is hermetic, deterministic, or bit-reproducible"
    "Any deviation from the supported matrix must be documented in the release notes."
)

assert_doc_contains(docs/NATIVE_BACKEND_PLAN.md
    "## Recommended first target"
    "platform triple: `x86_64-pc-windows-msvc`"
    "object format: `COFF`"
    "linker: `lld-link` via `clang -fuse-ld=lld`"
    "The primary CI path is the Windows x64 workflow in `.github/workflows/ci.yml`."
    "Self-hosting does not change that production target."
    "stage-1 native compiler, then compiled again by stage 1 into a stage-2 native compiler"
    "C emission may be a temporary migration aid, but it is not the final bootstrap evidence"
    "support the concrete layouts and runtime boundaries needed by the Evident compiler package described in `docs/BOOTSTRAP_PLAN.md`"
    "runs the read-only release source-tree audit before configure/build/test"
    "records the release source-tree audit status, runner image OS identifying Windows plus non-empty image version, Visual Studio metadata, MSVC x64 compiler banner, resolved tool paths, tool-version output identifying CMake, Ninja, clang, and LLD, compiler version output matching the release ZIP version, expected compiler toolchain fields with a selected driver that identifies clang, and release ZIP filename, size, and SHA256 in validated release evidence before upload"
    "revalidates the downloaded ZIP, checksum sidecar, and release evidence before provenance attestation generation"
)

assert_doc_contains(docs/COMPILER_FINISH_PLAN.md
    "passed `403/403` tests."
    "CI workflow, release-docs, CTest total, invalid corpus, test corpus registration, and C++ design escape-hatch contract validation"
    "CTest total contract"
    "release source-tree contract"
    "invalid corpus registration contract"
    "test corpus registration contract"
    "unsafe ZIP-entry validation has local negative coverage"
    "release source-tree audit catches dirty release branches, tracked generated build-output paths, root-level in-source CMake/Ninja/CTest/CPack artifacts, release ZIP/checksum/evidence artifacts, and ignored local-only artifacts before tagging"
    "CI runs that same release source-tree audit before configure/build/test"
    "Install validation now rejects unsafe or duplicate expected install allowlist paths"
    "unexpected installed files or directories"
    "validates the installed compiler as a PE executable"
    "unsafe expected install allowlist paths and unexpected installed payloads have local negative coverage"
    "unsafe or duplicate expected package-entry allowlist paths"
    "validates the packaged compiler as a PE executable"
    "unsafe expected allowlist entries"
    "empty path components"
    "empty-component expected allowlist entries"
    "checksum writer rejects non-ZIP package paths and misplaced checksum output paths"
    "package path names a `.zip` archive"
    "verifies the `.sha256` sidecar path"
    "rejects non-ZIP package paths"
    "canonical one-line sidecar format after CRLF/LF normalization"
    "misplaced checksum sidecar path"
    "sidecar naming a different package"
    "sidecar missing the final newline"
    "extra trailing blank lines"
    "bare package-root entries without a trailing slash"
    "validates that pair with the shared package checksum validator before upload"
    "rechecks the downloaded ZIP/checksum pair with the same validator before attestation"
    "revalidates the downloaded release evidence against the downloaded ZIP filename, byte size, SHA256, and `GITHUB_SHA` before provenance attestation generation and verification"
    "package filename, size, and SHA256 in `[release ZIP]`"
    "compiler version output matching the release ZIP version"
    "MSVC `cl` output identifying x64 target architecture"
    "tool-version output identifying CMake, Ninja, clang, and LLD"
    "expected compiler toolchain fields with a selected driver that identifies clang and checked-toolchain version probes identifying clang and LLD"
    "runner image OS identifying Windows and non-empty image version"
    "release source-tree audit status inside `[release source tree audit]`"
    "selected Visual Studio path and version inside `[vswhere]`"
    "rejects malformed release package names, malformed commit SHAs, evidence commits that do not match the expected source commit, missing runner image values, runner image OS that does not identify Windows, missing release source-tree audit status, incomplete Visual Studio metadata"
    "mismatched top-level release scope fields"
    "duplicate singleton provenance fields"
    "duplicate, unexpected, or out-of-order evidence sections"
    "MSVC compiler evidence that does not identify x64 target architecture"
    "tool-version output that does not identify CMake, Ninja, clang, or LLD"
    "missing or mismatched compiler toolchain fields"
    "selected clang driver output that does not identify clang"
    "empty compiler toolchain version-probe lines"
    "checked-toolchain version output that does not identify clang or LLD"
    "extra validated commands, package detail lines before `[release ZIP]`, misplaced package details, misplaced or stale CTest pass summaries, and relative tool paths in release evidence"
    "missing shared checksum validation before upload or attestation"
    "pins every remote action reference to a full commit SHA"
    "rejects mutable official or third-party action tags"
    "disables persisted checkout credentials"
    "keeps the build job `GITHUB_TOKEN` at `contents: read`"
    "unexpected `GITHUB_TOKEN` write permissions"
    "persisted checkout credentials"
    "push-only attestation conditions"
    "source-tree audit omissions or misordering"
    "`CMakePresets.json`, `.github/workflows/ci.yml`, and `docs/RELEASE_CHECKLIST.md` define the primary Windows x64 validation and release path"
    "Maintain the supported Windows x64 host/target matrix as a tested release-docs contract"
    "### 3. Self-Hosting Compiler"
    "stage-1 compiler rebuilds the same Evident compiler package"
    "### Bootstrap"
    "The repository is not self-hosting yet. The current compiler is a C++23 seed compiler."
    "`docs/BOOTSTRAP_PLAN.md` defines the bootstrap target"
    "### Milestone 7: Self-Hosting / Bootstrap"
    "Do not call the compiler self-hosting or bootstrap-capable"
    "The compiler can bootstrap itself through the documented seed, stage-1, and stage-2 process."
    "package identity, a deterministic source-discovery plan, an original-file diagnostic anchor"
    "It now also models the host runtime, environment, and bootstrap stage-provenance/equivalence records"
    "the package identity is derived from the bootstrap environment surface"
)

assert_doc_contains(docs/BOOTSTRAP_PLAN.md
    "# Bootstrap Plan"
    "The current repository is a C++23 seed compiler."
    "Evident can be called bootstrap-capable only when all of the following are true"
    "The C++ seed compiler can compile that Evident package into a stage-1 compiler executable."
    "The stage-1 compiler can compile the same Evident compiler package into a stage-2 compiler executable."
    "The stage-2 compiler passes the same required conformance, diagnostics, native emission, package, and release-contract tests as the seed-built compiler."
    "The compiler is not yet self-hosting."
    "initial Evident package outline at `bootstrap/compiler`"
    "That package is a compilable bootstrap scaffold, not a compiler implementation."
    "package identity, a deterministic source-discovery plan, an original-file diagnostic anchor"
    "initial lexical token stream data, parsed package syntax data, and a semantic symbol catalog"
    "Its package identity is derived from the bootstrap environment surface"
    "host file, path, environment, and tool boundary data plus bootstrap stage-provenance and equivalence records"
    "`run_bootstrap_compiler_scaffold`"
    "C emission can remain a temporary debugging or migration aid, but it is not the production bootstrap proof."
    "Bootstrap work must preserve explicit permits, proof construction, affine discipline, consequence-first naming, and boundary-local collapse of foreign ambiguity."
)

assert_doc_does_not_contain(docs/COMPILER_FINISH_PLAN.md
    "Decide and document the supported host/target matrix for the subset release."
)
