if(NOT DEFINED EXPECTED_MACHINE_HEX)
    set(EXPECTED_MACHINE_HEX "6486")
endif()

if(NOT DEFINED EXPECTED_OPTIONAL_MAGIC_HEX)
    set(EXPECTED_OPTIONAL_MAGIC_HEX "0b02")
endif()

if(NOT DEFINED EXPECTED_OPTIONAL_HEADER_SIZE_HEX)
    set(EXPECTED_OPTIONAL_HEADER_SIZE_HEX "f000")
endif()

if(NOT DEFINED EXPECTED_CHARACTERISTICS_HEX)
    set(EXPECTED_CHARACTERISTICS_HEX "2200")
endif()

if(NOT DEFINED EXPECTED_SUBSYSTEM_HEX)
    set(EXPECTED_SUBSYSTEM_HEX "0300")
endif()

if(NOT DEFINED EXPECTED_FIRST_SECTION_NAME_HEX)
    set(EXPECTED_FIRST_SECTION_NAME_HEX "2e74657874000000")
endif()

if(NOT DEFINED EXPECTED_FIRST_SECTION_CHARACTERISTICS_HEX)
    set(EXPECTED_FIRST_SECTION_CHARACTERISTICS_HEX "20000060")
endif()

function(read_u16le_hex input_hex output_var)
    string(LENGTH "${input_hex}" input_len)
    if(NOT input_len EQUAL 4)
        message(FATAL_ERROR "internal test error: expected 2 bytes of hex, got '${input_hex}'")
    endif()
    string(SUBSTRING "${input_hex}" 2 2 b1)
    string(SUBSTRING "${input_hex}" 0 2 b0)
    math(EXPR value "0x${b1}${b0}")
    set(${output_var} "${value}" PARENT_SCOPE)
endfunction()

function(read_u32le_hex input_hex output_var)
    string(LENGTH "${input_hex}" input_len)
    if(NOT input_len EQUAL 8)
        message(FATAL_ERROR "internal test error: expected 4 bytes of hex, got '${input_hex}'")
    endif()
    string(SUBSTRING "${input_hex}" 6 2 b3)
    string(SUBSTRING "${input_hex}" 4 2 b2)
    string(SUBSTRING "${input_hex}" 2 2 b1)
    string(SUBSTRING "${input_hex}" 0 2 b0)
    math(EXPR value "0x${b3}${b2}${b1}${b0}")
    set(${output_var} "${value}" PARENT_SCOPE)
endfunction()

function(assert_pe_executable_file output_path)
    if(NOT EXISTS "${output_path}")
        message(FATAL_ERROR "expected emitted executable does not exist: ${output_path}")
    endif()

    file(SIZE "${output_path}" output_size)
    if(output_size LESS 128)
        message(FATAL_ERROR "expected emitted PE executable to be at least 128 bytes: ${output_path}")
    endif()

    file(READ "${output_path}" mz_hex OFFSET 0 LIMIT 2 HEX)
    if(NOT mz_hex STREQUAL "4d5a")
        message(FATAL_ERROR "PE DOS signature mismatch for ${output_path}\nexpected: 4d5a\nactual: ${mz_hex}")
    endif()

    file(READ "${output_path}" pe_offset_hex OFFSET 60 LIMIT 4 HEX)
    read_u32le_hex("${pe_offset_hex}" pe_offset)
    math(EXPR minimum_header_end "${pe_offset} + 26")
    if(output_size LESS minimum_header_end)
        message(FATAL_ERROR "PE header offset points beyond emitted executable size: ${output_path}")
    endif()

    file(READ "${output_path}" pe_signature_hex OFFSET ${pe_offset} LIMIT 4 HEX)
    if(NOT pe_signature_hex STREQUAL "50450000")
        message(FATAL_ERROR "PE signature mismatch for ${output_path}\nexpected: 50450000\nactual: ${pe_signature_hex}")
    endif()

    math(EXPR machine_offset "${pe_offset} + 4")
    file(READ "${output_path}" machine_hex OFFSET ${machine_offset} LIMIT 2 HEX)
    if(NOT machine_hex STREQUAL EXPECTED_MACHINE_HEX)
        message(FATAL_ERROR
            "PE machine mismatch for ${output_path}\nexpected: ${EXPECTED_MACHINE_HEX}\nactual: ${machine_hex}")
    endif()

    math(EXPR sections_offset "${pe_offset} + 6")
    file(READ "${output_path}" section_count_hex OFFSET ${sections_offset} LIMIT 2 HEX)
    read_u16le_hex("${section_count_hex}" section_count)
    if(section_count LESS 1)
        message(FATAL_ERROR "PE executable has no sections: ${output_path}")
    endif()

    math(EXPR optional_header_size_offset "${pe_offset} + 20")
    file(READ "${output_path}" optional_header_size_hex OFFSET ${optional_header_size_offset} LIMIT 2 HEX)
    if(NOT optional_header_size_hex STREQUAL EXPECTED_OPTIONAL_HEADER_SIZE_HEX)
        message(FATAL_ERROR
            "PE optional-header size mismatch for ${output_path}\nexpected: ${EXPECTED_OPTIONAL_HEADER_SIZE_HEX}\nactual: ${optional_header_size_hex}")
    endif()
    read_u16le_hex("${optional_header_size_hex}" optional_header_size)
    math(EXPR optional_header_end "${pe_offset} + 24 + ${optional_header_size}")
    if(output_size LESS optional_header_end)
        message(FATAL_ERROR "PE optional header extends beyond emitted executable size: ${output_path}")
    endif()

    math(EXPR characteristics_offset "${pe_offset} + 22")
    file(READ "${output_path}" characteristics_hex OFFSET ${characteristics_offset} LIMIT 2 HEX)
    if(NOT characteristics_hex STREQUAL EXPECTED_CHARACTERISTICS_HEX)
        message(FATAL_ERROR
            "PE characteristics mismatch for ${output_path}\nexpected: ${EXPECTED_CHARACTERISTICS_HEX}\nactual: ${characteristics_hex}")
    endif()

    math(EXPR optional_magic_offset "${pe_offset} + 24")
    file(READ "${output_path}" optional_magic_hex OFFSET ${optional_magic_offset} LIMIT 2 HEX)
    if(NOT optional_magic_hex STREQUAL EXPECTED_OPTIONAL_MAGIC_HEX)
        message(FATAL_ERROR
            "PE optional-header magic mismatch for ${output_path}\nexpected: ${EXPECTED_OPTIONAL_MAGIC_HEX}\nactual: ${optional_magic_hex}")
    endif()

    math(EXPR entry_point_offset "${pe_offset} + 40")
    file(READ "${output_path}" entry_point_hex OFFSET ${entry_point_offset} LIMIT 4 HEX)
    read_u32le_hex("${entry_point_hex}" entry_point)
    if(entry_point EQUAL 0)
        message(FATAL_ERROR "PE executable has a zero address-of-entry-point: ${output_path}")
    endif()

    math(EXPR size_of_image_offset "${pe_offset} + 80")
    file(READ "${output_path}" size_of_image_hex OFFSET ${size_of_image_offset} LIMIT 4 HEX)
    read_u32le_hex("${size_of_image_hex}" size_of_image)
    if(size_of_image LESS 1)
        message(FATAL_ERROR "PE executable reports an empty image size: ${output_path}")
    endif()

    math(EXPR size_of_headers_offset "${pe_offset} + 84")
    file(READ "${output_path}" size_of_headers_hex OFFSET ${size_of_headers_offset} LIMIT 4 HEX)
    read_u32le_hex("${size_of_headers_hex}" size_of_headers)
    if(size_of_headers LESS optional_header_end)
        message(FATAL_ERROR "PE size-of-headers is smaller than the parsed headers: ${output_path}")
    endif()
    if(output_size LESS size_of_headers)
        message(FATAL_ERROR "PE size-of-headers extends beyond emitted executable size: ${output_path}")
    endif()

    math(EXPR subsystem_offset "${pe_offset} + 92")
    file(READ "${output_path}" subsystem_hex OFFSET ${subsystem_offset} LIMIT 2 HEX)
    if(NOT subsystem_hex STREQUAL EXPECTED_SUBSYSTEM_HEX)
        message(FATAL_ERROR
            "PE subsystem mismatch for ${output_path}\nexpected: ${EXPECTED_SUBSYSTEM_HEX}\nactual: ${subsystem_hex}")
    endif()

    math(EXPR section_table_offset "${pe_offset} + 24 + ${optional_header_size}")
    math(EXPR section_table_end "${section_table_offset} + (${section_count} * 40)")
    if(output_size LESS section_table_end)
        message(FATAL_ERROR "PE section table extends beyond emitted executable size: ${output_path}")
    endif()
    if(size_of_headers LESS section_table_end)
        message(FATAL_ERROR "PE size-of-headers is smaller than the parsed section table: ${output_path}")
    endif()

    math(EXPR last_section_index "${section_count} - 1")
    foreach(section_index RANGE 0 ${last_section_index})
        math(EXPR section_offset "${section_table_offset} + (${section_index} * 40)")

        file(READ "${output_path}" section_name_hex OFFSET ${section_offset} LIMIT 8 HEX)
        if(section_name_hex STREQUAL "0000000000000000")
            message(FATAL_ERROR "PE section ${section_index} has an empty name: ${output_path}")
        endif()

        math(EXPR section_virtual_size_offset "${section_offset} + 8")
        file(READ "${output_path}" section_virtual_size_hex OFFSET ${section_virtual_size_offset} LIMIT 4 HEX)
        read_u32le_hex("${section_virtual_size_hex}" section_virtual_size)
        if(section_virtual_size LESS 1)
            message(FATAL_ERROR "PE section ${section_index} has no virtual size: ${output_path}")
        endif()

        math(EXPR section_virtual_address_offset "${section_offset} + 12")
        file(READ "${output_path}" section_virtual_address_hex OFFSET ${section_virtual_address_offset} LIMIT 4 HEX)
        read_u32le_hex("${section_virtual_address_hex}" section_virtual_address)
        if(section_virtual_address LESS 1)
            message(FATAL_ERROR "PE section ${section_index} has no virtual address: ${output_path}")
        endif()

        math(EXPR section_raw_size_offset "${section_offset} + 16")
        file(READ "${output_path}" section_raw_size_hex OFFSET ${section_raw_size_offset} LIMIT 4 HEX)
        read_u32le_hex("${section_raw_size_hex}" section_raw_size)

        math(EXPR section_raw_pointer_offset "${section_offset} + 20")
        file(READ "${output_path}" section_raw_pointer_hex OFFSET ${section_raw_pointer_offset} LIMIT 4 HEX)
        read_u32le_hex("${section_raw_pointer_hex}" section_raw_pointer)

        if(section_raw_size GREATER 0)
            if(section_raw_pointer LESS size_of_headers)
                message(FATAL_ERROR "PE section ${section_index} raw data starts before the end of headers: ${output_path}")
            endif()

            math(EXPR section_raw_end "${section_raw_pointer} + ${section_raw_size}")
            if(output_size LESS section_raw_end)
                message(FATAL_ERROR "PE section ${section_index} raw data extends beyond emitted executable size: ${output_path}")
            endif()

            if(section_index GREATER 0)
                math(EXPR previous_last_section_index "${section_index} - 1")
                foreach(previous_section_index RANGE 0 ${previous_last_section_index})
                    math(EXPR previous_section_offset "${section_table_offset} + (${previous_section_index} * 40)")

                    math(EXPR previous_section_raw_size_offset "${previous_section_offset} + 16")
                    file(READ "${output_path}" previous_section_raw_size_hex OFFSET ${previous_section_raw_size_offset} LIMIT 4 HEX)
                    read_u32le_hex("${previous_section_raw_size_hex}" previous_section_raw_size)

                    if(previous_section_raw_size GREATER 0)
                        math(EXPR previous_section_raw_pointer_offset "${previous_section_offset} + 20")
                        file(READ "${output_path}" previous_section_raw_pointer_hex OFFSET ${previous_section_raw_pointer_offset} LIMIT 4 HEX)
                        read_u32le_hex("${previous_section_raw_pointer_hex}" previous_section_raw_pointer)
                        math(EXPR previous_section_raw_end "${previous_section_raw_pointer} + ${previous_section_raw_size}")

                        if(section_raw_pointer LESS previous_section_raw_end AND previous_section_raw_pointer LESS section_raw_end)
                            message(FATAL_ERROR
                                "PE section raw data ranges overlap in ${output_path}: section ${previous_section_index} and section ${section_index}")
                        endif()
                    endif()
                endforeach()
            endif()
        endif()
    endforeach()

    file(READ "${output_path}" first_section_name_hex OFFSET ${section_table_offset} LIMIT 8 HEX)
    if(NOT first_section_name_hex STREQUAL EXPECTED_FIRST_SECTION_NAME_HEX)
        message(FATAL_ERROR
            "PE first-section name mismatch for ${output_path}\nexpected: ${EXPECTED_FIRST_SECTION_NAME_HEX}\nactual: ${first_section_name_hex}")
    endif()

    math(EXPR first_section_virtual_size_offset "${section_table_offset} + 8")
    file(READ "${output_path}" first_section_virtual_size_hex OFFSET ${first_section_virtual_size_offset} LIMIT 4 HEX)
    read_u32le_hex("${first_section_virtual_size_hex}" first_section_virtual_size)
    if(first_section_virtual_size LESS 1)
        message(FATAL_ERROR "PE first .text section has no virtual size: ${output_path}")
    endif()

    math(EXPR first_section_virtual_address_offset "${section_table_offset} + 12")
    file(READ "${output_path}" first_section_virtual_address_hex OFFSET ${first_section_virtual_address_offset} LIMIT 4 HEX)
    read_u32le_hex("${first_section_virtual_address_hex}" first_section_virtual_address)
    if(first_section_virtual_address LESS 1)
        message(FATAL_ERROR "PE first .text section has no virtual address: ${output_path}")
    endif()

    math(EXPR first_section_raw_size_offset "${section_table_offset} + 16")
    file(READ "${output_path}" first_section_raw_size_hex OFFSET ${first_section_raw_size_offset} LIMIT 4 HEX)
    read_u32le_hex("${first_section_raw_size_hex}" first_section_raw_size)
    if(first_section_raw_size LESS 1)
        message(FATAL_ERROR "PE first .text section has no raw data: ${output_path}")
    endif()

    math(EXPR first_section_raw_pointer_offset "${section_table_offset} + 20")
    file(READ "${output_path}" first_section_raw_pointer_hex OFFSET ${first_section_raw_pointer_offset} LIMIT 4 HEX)
    read_u32le_hex("${first_section_raw_pointer_hex}" first_section_raw_pointer)
    if(first_section_raw_pointer LESS size_of_headers)
        message(FATAL_ERROR "PE first .text section raw data starts before the end of headers: ${output_path}")
    endif()
    math(EXPR first_section_raw_end "${first_section_raw_pointer} + ${first_section_raw_size}")
    if(output_size LESS first_section_raw_end)
        message(FATAL_ERROR "PE first .text section raw data extends beyond emitted executable size: ${output_path}")
    endif()

    math(EXPR first_section_characteristics_offset "${section_table_offset} + 36")
    file(READ "${output_path}" first_section_characteristics_hex OFFSET ${first_section_characteristics_offset} LIMIT 4 HEX)
    if(NOT first_section_characteristics_hex STREQUAL EXPECTED_FIRST_SECTION_CHARACTERISTICS_HEX)
        message(FATAL_ERROR
            "PE first .text section characteristics mismatch for ${output_path}\nexpected: ${EXPECTED_FIRST_SECTION_CHARACTERISTICS_HEX}\nactual: ${first_section_characteristics_hex}")
    endif()

    math(EXPR first_section_virtual_end "${first_section_virtual_address} + ${first_section_virtual_size}")
    if(entry_point LESS first_section_virtual_address)
        message(FATAL_ERROR "PE entry point is before the first .text section: ${output_path}")
    endif()
    if(NOT entry_point LESS first_section_virtual_end)
        message(FATAL_ERROR "PE entry point is not inside the first .text section: ${output_path}")
    endif()
endfunction()
